### ISSUE TITLE
Warning! Error encountered during contract execution [execution reverted] 

### ISSUE THREAD

**Issue by NL647** [bancorprotocol/fastlane-bot#195]
Hello, 
i  m using the bot with default settings and got 6 : Warning! Error encountered during contract execution [execution reverted] .
The gas fee are taken but transaction is aborted.
Example: tx hash `0x9d172dd0413be135a18fabff76d8b150f756786305e3f7e016fc64c65e7af0fe`

is there a way to avoid that?

**Comment by Lesigh-3100** [comment]
Hi, thanks for submitting your question. 

What happened is that the pool values changed from when you calculated the arbitrage, so the minimum return specified from the first trade was not received, causing the transaction to fail. This is actually a good thing in that it failed early in the process, saving you some ETH gas costs. 

This could have happened due to a trade on the pool in the block before your arbitrage trade, causing your arbitrage transaction to no longer be valid. 

This has generally become less frequent over time, but it does still happen on occasion. If you want to continue the discussion on how to improve your bot, or have any followup questions, feel free to start a conversation on the Bancor Developer's Telegram group:  [](https://t.me/BancorDevelopers)
