### ISSUE TITLE
Minor optimization in multicaller

### ISSUE THREAD

**Issue by Lesigh-3100** [bancorprotocol/fastlane-bot#348]
## Enhancement Description
Minor optimization to multicaller class - avoid reinitialization of multicall contract. 

## Rationale
This upgrade reuses the multicall contract instead of recreating it multiple times. This is a small change that results in a performance boost.

## Impact Analysis
- Automated Tests: Implications on testing (new/changed)
None
- Risks: What are the risks associated with this enhancement?
Can't think of anything.

- Performance: Expected performance impacts and how to measure them
This improves performance when using multicall. This is can be seen in the avg time per iteration. 

- Monitoring: Changes required in the monitoring system
None
- Logging: Do we need additional logs?
No
- Documentation: Updates or new documentation needed?
No

**Comment by barakman** [comment]
This issue cannot be explained as the result of calling `web3.eth.contract(...)` twice instead of once at some place in the code, because the time it takes to create the logical object which represents the multi-call contract is approximately 0.01 of a second (see python script below).

If there is indeed a notable performance improvement as a result of fixing the above, then it implies either one of two options:
1. The place in the code where this logical object is created, is called repeatedly from somewhere else in the code
2. The performance measurement itself is biased due to a "fluctuating" (inconsistent) environment-state

In order to investigate option 1 properly, one needs to follow every execution path which leads to that point in the code, and verify that it is not unnecessarily repeated over and over.

This can be done by searching for occurrences of `multicall(` in the code (case-sensitive AND whole-word), since that's the function where the logical object is created twice instead of once.

Here are some of the different execution paths in which that function is called:

1:
```
multicall_helper -->
    multicall_every_iteration -->
       run (called once per iteration)
```
2:
```
get_strats_by_contract -->
    get_strategies -->
        update_carbon -->
            get_rows_to_update -->
                async_handle_initial_iteration -->
                   run (called once per iteration)
```
3:
```
get_strats_by_contract -->
    get_strategies -->
        update_carbon -->
            get_rows_to_update -->
                handle_initial_iteration (not called anywhere)
```
4:
```
get_fees_by_pair -->
    get_fee_pairs -->
        set_carbon_v1_fee_pairs -->
            BaseManager.__post_init__ -->
                main (called once per execution)
```
5:
```
get_fees_by_pair -->
    get_fee_pairs -->
        update_carbon -->
            get_rows_to_update -->
                async_handle_initial_iteration -->
                   run (called once per iteration)
```
6:
```
get_fees_by_pair -->
    get_fee_pairs -->
        update_carbon -->
            get_rows_to_update -->
                handle_initial_iteration (not called anywhere)
```
7:
```
get_fees_by_pair -->
    get_fee_pairs -->
        handle_pair_created -->
            Manager.update_from_event -->
                Manager.update -->
                    Hard to say, but it seems to be called only from itself, upon an exception
```
8:
get_fees_by_pair -->
    get_fee_pairs -->
        handle_trading_fee_updated -->
            Manager.update_from_event -->
                Manager.update -->
                    Hard to say, but it seems to be called only from itself, upon an exception
```
And here is a python script for measuring the time it takes for creating the logical object:
```
from web3 import Web3
from time import time

MULTICALL_ABI = [ ... ]
MULTICALL_CONTRACT_ADDRESS = "0x5BA1e12693Dc8F9c48aAD8770482f4739bEeD696"

web3 = Web3(Web3.HTTPProvider("YOUR_NODE_URL"))

start = time()
contract = web3.eth.contract(abi=MULTICALL_ABI, address=MULTICALL_CONTRACT_ADDRESS)
end = time()

print(end - start)
```
