### ISSUE TITLE
Main Loop Function / Exception Handling

### ISSUE THREAD

**Issue by sklbancor** [bancorprotocol/fastlane-bot#489]
This is the main loop function:

 ```  
  def run_continuous_mode(
        self,
        flashloan_tokens: List[str],
        arb_mode: str,
        run_data_validator: bool,
        randomizer: int,
    ):
        """
        Run the bot in continuous mode.

        Parameters
        ----------
        flashloan_tokens: List[str]
            The flashloan tokens
        arb_mode: bool
            The arb mode
        """
        while True:
            try:
                CCm = self.get_curves()
                tx_hash, cids, route_struct = self._run(
                    flashloan_tokens,
                    CCm,
                    arb_mode=arb_mode,
                    data_validator=run_data_validator,
                    randomizer=randomizer,
                )
                if tx_hash and tx_hash[0]:
                    self.ConfigObj.logger.info(f"Arbitrage executed [hash={tx_hash}]")

                time.sleep(self.polling_interval)
            except self.NoArbAvailable as e:
                self.ConfigObj.logger.debug(f"[bot:run:continuous] {e}")
            except Exception as e:
                self.ConfigObj.logger.error(f"[bot:run:continuous] {e}")
                time.sleep(self.polling_interval)
```

Firstly, it has an incomplete docstring which should be addressed. 

Secondly -- NoArbAvailable should not really be an exception; this is a normal course of business, and really should not throw, by passing whatever code we expect to run. This should be fixed.

Most importantly however -- there should be a bot mode for testing where exceptions are fatal, and the bot terminates with a full stack trace rather than with a cryptic print out of the exception, `str(e)`

**Comment by barakman** [comment]
```
Secondly -- NoArbAvailable should not really be an exception; this is a normal course of business, and really should not throw, by passing whatever code we expect to run. This should be fixed.
```
That's exactly why `NoArbAvailable` is used here - printing a short message instead of treating this scenario as an erroneous one.

---

```
Most importantly however -- there should be a bot mode for testing where exceptions are fatal, and the bot terminates with a full stack trace rather than with a cryptic print out of the exception, str(e)
```
The bot should not terminate on every fatal exception, for example:
- When there is no network connection for a few seconds
- When the node throws an error for exceeding maximum amount of requests permitted

Lastly - note that function `run_continuous_mode` was removed from the code since it hadn't been in use.
Instead, function `bot.run` performs what used to be in function `run_single_mode`.
It catches only the `NoArbAvailable` exception, which it handles gracefully (only message-printing).
Any other exception would be raised to the caller - function `main.run`.
